### PR TITLE
replaced occurrences of node.slice with node.full_name

### LINKED ISSUE #1130: Switch from using `node.slice` to `node.full_name` for constant paths
Ruby allows you to do the following for constant paths:

```ruby
Foo:: # Some comment
  Bar:: # Other comment
    Baz
```

In those cases, `node.slice` will not return the correct constant name `Foo::Bar::Baz` since the slice includes the comments. Prism recently got support for `#full_name` on constant path nodes, so let's use that instead.

### PR DESCRIPTION
**Pull request by haiderashfaq**
Resolves #1130 

replaced occurrences of `node.slice` with `node.full_name`

### CODE REVIEW

**Comment by haiderashfaq** [comment]
> looks like our RBI is missing the definition for `full_name`

yes

**Comment by haiderashfaq** [comment]
> Thank you very much for the contribution!
> 
> It looks like our RBI is missing the definition for `full_name`. If you run `bin/tapioca gem prism`, does it re-generate the RBI with those method declarations included?

yes

**Comment by vinistock** [comment]
This PR is almost there. Just missing a few more occurrences for the indexer here:

- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L59
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L69
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L79
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L89
- [ ] For this one, we'll need to split `Prism::ConstantReadNode` and `Prism::ConstantPathNode` into separate branches of the `case` statement https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L186
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L198
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L206
- [ ] https://github.com/Shopify/ruby-lsp/blob/604fe8a39d361cf57a83405afc2bcb6a8dbe46f3/lib/ruby_indexer/lib/ruby_indexer/visitor.rb#L219

**Comment by vinistock** [comment]
> I don't think full_name is available on Prism::Location. There are few occurrences mentioned above that will be instance of Prism::Location.

`node.location.slice` and `node.slice` are the same thing. In those instances of `node.location.slice` you can just switch to `node.full_name`.

**Comment by vinistock** [comment]
This PR got unblocked now that we upgraded to Prism v0.18.0. Sorry, I forgot to warn you @haiderashfaq.

Now `full_name` will raise an error if any of the constant parts are dynamic https://github.com/ruby/prism/pull/1742. So we need to rescue that error everywhere we call `full_name`.

@haiderashfaq, please let us know if you'd like to finish this PR.

@giovannism20 let's wait for the original creator of the PR, if he wishes to finish this.

**Comment by haiderashfaq** [comment]
> This PR got unblocked now that we upgraded to Prism v0.18.0. Sorry, I forgot to warn you @haiderashfaq.
> 
> Now `full_name` will raise an error if any of the constant parts are dynamic [ruby/prism#1742](https://github.com/ruby/prism/pull/1742). So we need to rescue that error everywhere we call `full_name`.
> 
> @haiderashfaq, please let us know if you'd like to finish this PR.
> 
> @giovannism20 let's wait for the original creator of the PR, if he wishes to finish this.

what should be the behavior for rescue? should it fallback to node.slice?

**Comment by haiderashfaq** [comment]
Working opening a new PR

**Pull request closed without merging**
