### PR TITLE
Fix typo in the neovim setup lua script

### PR DESCRIPTION
**Pull request by alxekb**
### Motivation

There is a tiny typo in the neovim setup which breaks LSP configuration. It's better to have it fixed. 👍🏻

### CODE REVIEW

**Review by st0012 — APPROVED** [review]
Thanks!

**Comment by st0012** [comment]
@alxekb Can you sign the CLA please?

**Comment by alxekb** [comment]
@st0012 I'm sorry, that was a hiccup. Still can't make it run. Will update this PR if I get some progress.

**Comment by vinistock** [comment]
Closing this PR for now. Please re-open if you discover what was breaking the config.

**Pull request closed without merging**
