### PR TITLE
Make `RubyIndexer::Index#entries` public

### PR DESCRIPTION
**Pull request by andyw8**
### Motivation

We commonly access the index's entries in tests, but we need to awkwardly read the internal state of the index. Let's make this public instead.

I've added a note to highlight that this is only intended for tests.

This is a slight risk that addon authors could mis-use this API, but they could have circumvented the access control anyway if they wanted.

### Implementation

Add an `attr_reader`.

### Automated Tests

n/a

### Manual Tests

n/a

### CODE REVIEW

**Review by vinistock — CHANGES_REQUESTED** [review]
The decision to not make `@entries` public was very intentional. We don't want users of the API to interact with the internal state of the index without going through one of the public APIs, as someone could accidentally corrupt the internal state.

If we need a new API for some specific need, we can add it to the index, but we should not expose any of its internal state.

Because it's Ruby, one can always do something like `instance_variable_get`, but at least it communicates very clearly that they are reaching into non public internal state and could get into trouble.

**Comment by vinistock** [comment]
I wouldn't do that. The method will show up as available and people will only discover they are not supposed to use it when things break. I would honestly just keep the `instance_variable_get` occurrences we have in tests.

**Comment by Morriar** [comment]
You could return `@entries.dup` or just `@entries.values`

**Comment by andyw8** [comment]
I've pushed an update with @Morriar `dup` suggestion for consideration. (GH won't let me re-open since I force pushed).

**Pull request closed without merging**
