### PR TITLE
Fix behaviour of DocumentLink for when a gem has been removed

### PR DESCRIPTION
**Pull request by haroon26**
### Motivation

Issue #464

### Implementation

Early return in case of `resolve_version` returns `nil`

### CODE REVIEW

**Comment by Morriar** [comment]
👋 Hey @haroon26,

Thanks for your contribution.

You'll have to sign the CLA: https://github.com/Shopify/ruby-lsp/actions/runs/5525306052/jobs/10078761385?pr=809.

**Comment by haroon7v** [comment]
Hello @Morriar, I have done that already after the test was failed.

**Comment by haroon26** [comment]
I have signed the CLA!

**Comment by haroon26** [comment]
sure, I will add a test

**Pull request closed without merging**
